# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: IS212-SPM-G8T5

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04 # The operating system environment on which the job will run

    defaults:
      run:
        working-directory: ./backend/ # Change working directory to backend folder

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask_sqlalchemy flask-cors flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create test database
      run: |
        sudo /etc/init.d/mysql start
        mysql -h 127.0.0.1 -u root  -p < spm2.sql

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        python test_unittest.py

    - name: Run pytest
      run: |
        python -m pytest test_app.py
